language: php
php:
  - 5.3
  
env:
  - PSC_CMS=$HOME/builds/pscheit/psc-cms/bin/ PHPUNIT_TESTSUITE=true TRAVIS_CI=true
  
before_script:
  - mysql -e 'create database IF NOT EXISTS `psc-cms_tests`;'
  - php -f tests/update.schema.php
  
script: phpunit

notifications:
  irc: "irc.freenode.org#psc-cms"