language: php
php:
  - 5.3
  
env:
  - PSC_CMS=$HOME/builds/pscheit/psc-cms/bin
  
before_script:
  - mysql -e 'create database IF NOT EXISTS `psc-cms_tests`;'
  
script: php -f ./bin/cli.php test

notifications:
  irc: "irc.freenode.org#psc-cms"