language: php
php:
  - 5.3

branches:
  only:
    - master
env:
  - PSC_CMS=$HOME/builds/pscheit/psc-cms/etc/travis/
  
before_script:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev
  - vendor/bin/webforge register-package .
  - mysql -e 'create database IF NOT EXISTS `psc-cms_tests`;'
  - mysql -e 'create database IF NOT EXISTS `psc-cms`;'
  - php -f tests/inc.update-schema.php

script: phpunit

notifications:
  irc: "irc.freenode.org#webforge"
  mail: p.scheit@ps-webforge.com