language: php
php:
  - 5.4

branches:
  only:
    - master
env:
  - PSC_CMS=$HOME/build/pscheit/psc-cms/etc/travis/; COMPOSER_ROOT_VERSION=dev-master 

before_install:
  - composer self-update
  - composer require --no-update --no-interaction "pscheit/psc-cms-image:$COMPOSER_ROOT_VERSION"
  - composer install --prefer-source --no-interaction --dev

before_script:
  - vendor/bin/webforge register-package .
  - mysql -e 'create database IF NOT EXISTS `psc-cms_tests`;'
  - mysql -e 'create database IF NOT EXISTS `psc-cms`;'
  - php -f bin/cli.php compile:test-entities
  - php -f tests/inc.update-schema.php

script: phpunit

notifications:
  irc: "irc.freenode.org#webforge"
  mail: p.scheit@ps-webforge.com