language: php
php:
  - 5.6

branches:
  only:
    - master
env:
  - PSC_CMS=/home/travis/build/webforge-labs/psc-cms/etc/travis/

before_install:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source --no-interaction --dev

before_script:
  - vendor/bin/webforge register-package .
  - mysql -e 'create database IF NOT EXISTS `psc-cms_tests`;'
  - mysql -e 'create database IF NOT EXISTS `psc-cms`;'
  - php -f bin/cli.php compile:test-entities
  - php -f tests/inc.update-schema.php

script: phpunit

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@ps-webforge
  mail: p.scheit@ps-webforge.com